---
title: "Theory_second_edition"
author: "Issei Tsunoda"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Theory_second_edition}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
 
# Latent Gaussian (bi-normal) Assumption
## The Roll
- Determine hits rate and false rate
- Latent Gaussian variable is attached (related) with respect to each image (lesion)? or not attached since it is i.i.d., it is no need or same whether or not it is attached or not.
 
 
 Let $z$ be continuous parameter ${}^{  \dagger}$ representing the confidence level of reader (observer) who try to detect lesions from radiographs. The reason why we use the alphabet $z$ is it moves in the target space of the random variable distributed by two Gaussian distributions, one is a signal and the other is noise. Suppose that there are two random variables, one means signal and the other is noise. We shall denote the signal by $Y$ and noise by $X$;
 
 $$
 Y \sim \text{Normal}(\mu,\sigma ^2) \\
  X \sim \text{Normal}(0,1) \\
 $$
 
 We say that reader make hit $H_z$ with confidence level $z$ iff $Y>z$.
  We say that reader make false alarm $F_z$ with confidence level $z$ iff $X>z$.

 So, hit rate of reader is $\mathbb{P}(Y>z)$. On the other hand, false alarm rate is $\mathbb{P}(X>z)$. If we assume also that false rate can represent the poisson rate $\lambda(z)$, that is the number of false alarms $F_z$  with confidence level $z$ is distributed by $F_z \sim \text{Poisson}(\lambda(z))$
 Then the relation of $\mathbb{P}(X>z)$ and $\lambda(z)$ can be calculated via the probability of at lease one false alarms with confidence level $z$ which we shall denote by $\text{Prob}(F_z \neq 0)$ 
 
 $$\text{Prob}(F_z \neq 0)  =  \mathbb{P}(X>z)  = e^{ \lambda(z) } $$
I have to say this equation is not sufficiently explained in any paper or book.



 - $\dagger$: In practical theme, this is not continuous. It might consists perhaps 5 categories $z=z_1,z_2,z_3,z_4,z_5$ corresponding to "$z_5$ = definitely positive", "$z_4$= almost definitely positive", "$z_3$=equivocal","$z_2$=uncertainly positive" and "$z_1$=questionable,...but positive".
 
 
 
##  
